// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIl9lSxjdEOMMODU49NOAYeC5Fr4cXRsg',
    appId: '1:487807853291:web:dcd5cfb7b3f0112cf154ae',
    messagingSenderId: '487807853291',
    projectId: 'skywander-2xx52',
    authDomain: 'skywander-2xx52.firebaseapp.com',
    storageBucket: 'skywander-2xx52.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHQSQOxO-oI3g2GMc0n_Q1YJrGYsIAQ1E',
    appId: '1:487807853291:android:8631eb5f8bdda2f1f154ae',
    messagingSenderId: '487807853291',
    projectId: 'skywander-2xx52',
    storageBucket: 'skywander-2xx52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMnPIhFhnEz2WEhMSUqEqDWbRMPi7SOCw',
    appId: '1:487807853291:ios:34d982e4a6d90b81f154ae',
    messagingSenderId: '487807853291',
    projectId: 'skywander-2xx52',
    storageBucket: 'skywander-2xx52.appspot.com',
    iosClientId: '487807853291-hg3jj9d9a9si3dqt1d4djrtv60ag24jj.apps.googleusercontent.com',
    iosBundleId: 'com.example.skywanderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMnPIhFhnEz2WEhMSUqEqDWbRMPi7SOCw',
    appId: '1:487807853291:ios:ff221ab7f5cc4a29f154ae',
    messagingSenderId: '487807853291',
    projectId: 'skywander-2xx52',
    storageBucket: 'skywander-2xx52.appspot.com',
    iosClientId: '487807853291-67gors701jib2ro161vpqaq3k6f7nesp.apps.googleusercontent.com',
    iosBundleId: 'com.example.skywanderApp.RunnerTests',
  );
}
